// Build the cdn worker's static assets directory (#34):
//
//   public/v1.js              the snippet bundle from packages/snippet
//   public/v1.js.map
//   public/v1.<hash>.js       the same bytes, content-addressed (sha256, 8 hex)
//   public/v1.<hash>.js.map   (its sourceMappingURL comment points here)
//   public/version.json       { version, hash, builtAt }
//   public/_headers           the response headers for all of the above and
//                             /demo/*, applied by Workers static assets
//                             with no Worker invocation (#158)
//
// `pnpm --filter @proofql/cdn build`. Runs the snippet's own esbuild step
// (`buildSnippet` from @proofql/snippet) so the cdn always ships the source
// in the tree, then copies. Stale hashed copies from earlier local builds
// are removed so `wrangler deploy` uploads exactly one build; public/demo/
// (the committed demo site) is never touched.
//
// `buildCdn` is exported for the unit test (src/build.test.ts), which builds
// into a temp directory and asserts the file set and the manifest.
import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { buildSnippet } from "@proofql/snippet/scripts/build.mjs";

const here = dirname(fileURLToPath(import.meta.url));
/** Default output: workers/cdn/public. */
export const PUBLIC_DIR = resolve(here, "..", "public");

/** First 8 hex characters of the SHA-256 of `bytes`. */
export function contentHash(bytes) {
  return createHash("sha256").update(bytes).digest("hex").slice(0, 8);
}

/** Point the bundle's sourceMappingURL comment at `mapName`. */
export function retargetSourceMap(source, mapName) {
  return source.replace(
    /^\/\/# sourceMappingURL=.*$/m,
    `//# sourceMappingURL=${mapName}`,
  );
}

/** Files a previous build left in `dir` that this build replaces. */
export function isBuildOutput(name) {
  return (
    /^v1(\.[0-9a-f]{8})?\.js(\.map)?$/.test(name) ||
    name === "version.json" ||
    name === "_headers"
  );
}

// The header values below must equal src/handler.ts's (`cacheControlFor`,
// `securityHeaders`): the worker still answers what static assets do not
// (404s, OPTIONS, /health, /), and src/build.test.ts fails when the two
// disagree. This file is .mjs and cannot import the .ts module.
export const MUTABLE_CACHE_CONTROL =
  "public, max-age=300, stale-while-revalidate=86400";
export const IMMUTABLE_CACHE_CONTROL = "public, max-age=31536000, immutable";
const SNIPPET_CORS = [
  ["Access-Control-Allow-Origin", "*"],
  ["Access-Control-Allow-Methods", "GET, HEAD, OPTIONS"],
  ["Access-Control-Max-Age", "86400"],
  ["Cross-Origin-Resource-Policy", "cross-origin"],
];

/**
 * The `_headers` file (Workers static assets, #158). Every snippet load is
 * then served by the asset layer alone — free and unmetered — instead of
 * invoking the worker (`run_worker_first` is limited to `/health` in
 * wrangler.jsonc). Exact paths, not splats: two matching rules would join
 * their `Cache-Control` values with a comma, and the hashed name is known
 * here.
 *
 * @param {string} hash
 * @returns {string}
 */
export function headersFile(hash) {
  const nosniff = ["X-Content-Type-Options", "nosniff"];
  /** @type {[string, [string, string][]][]} */
  const rules = [
    [
      "/v1.js",
      [["Cache-Control", MUTABLE_CACHE_CONTROL], nosniff, ...SNIPPET_CORS],
    ],
    [
      "/v1.js.map",
      [["Cache-Control", MUTABLE_CACHE_CONTROL], nosniff, ...SNIPPET_CORS],
    ],
    [
      `/v1.${hash}.js`,
      [["Cache-Control", IMMUTABLE_CACHE_CONTROL], nosniff, ...SNIPPET_CORS],
    ],
    [
      `/v1.${hash}.js.map`,
      [["Cache-Control", IMMUTABLE_CACHE_CONTROL], nosniff, ...SNIPPET_CORS],
    ],
    ["/version.json", [["Cache-Control", MUTABLE_CACHE_CONTROL], nosniff]],
    ["/demo", [["Cache-Control", MUTABLE_CACHE_CONTROL], nosniff]],
    ["/demo/*", [["Cache-Control", MUTABLE_CACHE_CONTROL], nosniff]],
  ];
  const lines = [
    "# Generated by workers/cdn/scripts/build.mjs; do not edit (#158).",
    "# Static assets apply these with no Worker invocation.",
  ];
  for (const [path, headers] of rules) {
    lines.push(path);
    for (const [name, value] of headers) lines.push(`  ${name}: ${value}`);
  }
  return `${lines.join("\n")}\n`;
}

/**
 * @param {{ outDir?: string, now?: Date }} [options]
 * @returns {Promise<{ outDir: string, hash: string, version: string, files: string[] }>}
 */
export async function buildCdn({ outDir = PUBLIC_DIR, now = new Date() } = {}) {
  const bundlePath = await buildSnippet();
  const bundle = await readFile(bundlePath);
  const map = await readFile(`${bundlePath}.map`);
  // The snippet's version is the bundle's `window.ProofQL.version`; /health
  // and version.json report that, not this worker's own package version.
  const snippetPkg = JSON.parse(
    await readFile(
      createRequire(import.meta.url).resolve("@proofql/snippet/package.json"),
      "utf8",
    ),
  );

  const hash = contentHash(bundle);
  await mkdir(outDir, { recursive: true });
  for (const name of await readdir(outDir)) {
    if (isBuildOutput(name)) await rm(join(outDir, name));
  }

  const hashedName = `v1.${hash}.js`;
  const files = {
    "v1.js": bundle,
    "v1.js.map": map,
    [hashedName]: retargetSourceMap(
      bundle.toString("utf8"),
      `${hashedName}.map`,
    ),
    [`${hashedName}.map`]: map,
    "version.json": `${JSON.stringify(
      { version: snippetPkg.version, hash, builtAt: now.toISOString() },
      null,
      2,
    )}\n`,
    _headers: headersFile(hash),
  };
  for (const [name, contents] of Object.entries(files)) {
    await writeFile(join(outDir, name), contents);
  }
  return {
    outDir,
    hash,
    version: snippetPkg.version,
    files: Object.keys(files).sort(),
  };
}

if (
  process.argv[1] &&
  fileURLToPath(import.meta.url) === resolve(process.argv[1])
) {
  const result = await buildCdn();
  process.stdout.write(
    `built ${result.outDir}: ${result.files.join(", ")} (snippet ${result.version}, hash ${result.hash})\n`,
  );
}
