/**
 * Bindings the pipeline worker receives as `env` — one entry per binding in
 * wrangler.jsonc (hand-written rather than generated by `wrangler types`, so
 * the shape is reviewed with the config that declares it).
 */

export interface PipelineBindings {
  /** "local" | "preview" | "prod" — from `vars` in wrangler.jsonc. */
  ENVIRONMENT: string;
  /** Postgres via Hyperdrive; locally the docker compose database. */
  HYPERDRIVE: Hyperdrive;
  /** Query-result cache; purged for a project after its reviews are indexed. */
  CACHE: KVNamespace;
  /**
   * Workers AI for embeddings and sentiment. Bound in preview/prod only —
   * there is no local simulator — so code must treat it as optional.
   */
  AI?: Ai;
}

/**
 * Body of a `proofql-ingest` message. Placeholder until the push API (M1)
 * fixes the shape; the consumer today acks without reading it.
 */
export type IngestMessage = Record<string, unknown>;
