/**
 * Bindings the pipeline worker receives as `env` — one entry per binding in
 * wrangler.jsonc (hand-written rather than generated by `wrangler types`, so
 * the shape is reviewed with the config that declares it).
 *
 * The queue message body type lives in `@proofql/core` (`IngestMessage`),
 * shared with the producer in workers/api.
 */

import type { IngestMessage } from "@proofql/core";

export interface PipelineBindings {
  /** "local" | "preview" | "prod" — from `vars` in wrangler.jsonc. */
  ENVIRONMENT: string;
  /** Postgres via Hyperdrive; locally the docker compose database. */
  HYPERDRIVE: Hyperdrive;
  /** Query-result cache; purged for a project after its reviews are indexed. */
  CACHE: KVNamespace;
  /**
   * Producer side of the same queue this worker consumes: the cron sweep
   * (src/sweep.ts) re-enqueues reviews stuck with `indexed_at IS NULL`.
   */
  INGEST_QUEUE: Queue<IngestMessage>;
  /**
   * Workers AI for embeddings and sentiment. Bound in preview/prod only —
   * there is no local simulator — so code must treat it as optional.
   */
  AI?: Ai;
  /**
   * Google connector (#46; docs/google.md, docs/secrets.md). All optional:
   * the poller logs `google.poll.skipped` and does nothing until the three
   * credentials are set, so a deploy without them never breaks the cron.
   */
  /** base64 of 32 random bytes; AES-GCM key for `connections.credentials`. */
  CREDENTIALS_KEY?: string;
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  /** Endpoint overrides; unset ⇒ real Google. Locally all three point at the fake. */
  GOOGLE_OAUTH_BASE?: string;
  GOOGLE_TOKEN_URL?: string;
  GOOGLE_API_BASE?: string;
  /**
   * Places bootstrap refresh (#116; docs/places.md "Refresh"). The same key
   * the dashboard uses for the "Find your business on Google" card; unset
   * ⇒ the daily cron logs `places.refresh.skipped` and does nothing.
   */
  GOOGLE_PLACES_API_KEY?: string;
  /** Endpoint override; unset ⇒ `https://places.googleapis.com`. Locally the fake on :8803. */
  PLACES_API_BASE?: string;
  /**
   * The dashboard's uploads bucket (`proofql-uploads[-<env>]`), bound here
   * only so the daily account purge (#169, src/account-purge.ts) can delete
   * a purged workspace's `uploads/<projectId>/` prefixes. Optional in the
   * type: without it the purge still deletes the rows and R2 is left to the
   * bucket's 7-day lifecycle rule (infra/provisioning.md).
   */
  UPLOADS?: R2Bucket;
}
