/**
 * Bindings the api worker receives as `env` — one entry per binding in
 * wrangler.jsonc (hand-written rather than generated by `wrangler types`, so
 * the shape is reviewed with the config that declares it) — and the
 * per-request variables middleware attaches to the Hono context.
 */

import type {
  ApiKeyEnvironment,
  ApiKeyKind,
  IngestMessage,
} from "@proofql/core";
import type { Db } from "@proofql/db";

export interface ApiBindings {
  /** "local" | "preview" | "prod" — from `vars` in wrangler.jsonc. */
  ENVIRONMENT: string;
  /** Postgres via Hyperdrive; locally the docker compose database. */
  HYPERDRIVE: Hyperdrive;
  /** Query-result cache, shared with pipeline (purge) and dashboard (purge). */
  CACHE: KVNamespace;
  /** Producer side of `proofql-ingest`; workers/pipeline consumes. */
  INGEST_QUEUE: Queue<IngestMessage>;
  /**
   * Workers AI for query embeddings. Bound in preview/prod only — there is
   * no local simulator — so code must treat it as optional.
   */
  AI?: Ai;
}

/** What a resolved API key grants a request (set by `requireApiKey`). */
export interface AuthContext {
  apiKeyId: string;
  projectId: string;
  /** Scopes every row the request reads or writes. */
  environment: ApiKeyEnvironment;
  kind: ApiKeyKind;
}

export interface AppVariables {
  /** Echoed as `x-request-id` on every response; in every error envelope. */
  requestId: string;
  /** Lazily opens the database for this request (see src/db.ts). */
  getDb: () => Db;
  /** Present after `requireApiKey` ran. */
  auth: AuthContext;
}

/** Hono generic: bindings on `c.env`, variables on `c.var` / `c.get()`. */
export type AppEnv = { Bindings: ApiBindings; Variables: AppVariables };
