/**
 * Bindings the api worker receives as `env` — one entry per binding in
 * wrangler.jsonc (hand-written rather than generated by `wrangler types`, so
 * the shape is reviewed with the config that declares it) — and the
 * per-request variables middleware attaches to the Hono context.
 */

import type { EmbeddingProvider } from "@proofql/ai";
import type {
  ApiKeyEnvironment,
  ApiKeyKind,
  IngestMessage,
} from "@proofql/core";
import type { Db } from "@proofql/db";

import type { RateLimiters } from "./rate-limit.js";

export interface ApiBindings {
  /** "local" | "preview" | "prod" — from `vars` in wrangler.jsonc. */
  ENVIRONMENT: string;
  /** Postgres via Hyperdrive; locally the docker compose database. */
  HYPERDRIVE: Hyperdrive;
  /** Query-result cache, shared with pipeline (purge) and dashboard (purge). */
  CACHE: KVNamespace;
  /** Producer side of `proofql-ingest`; workers/pipeline consumes. */
  INGEST_QUEUE: Queue<IngestMessage>;
  /**
   * Workers AI for query embeddings. Bound in preview/prod only — there is
   * no local simulator — so code must treat it as optional.
   */
  AI?: Ai;
  /**
   * Cloudflare rate limiting bindings, one per key kind (`ratelimits` in
   * wrangler.jsonc). Optional: absent (unit tests, a wrangler without the
   * config) the worker falls back to an in-memory limiter per isolate so
   * the behavior stays observable locally. See src/rate-limit.ts.
   */
  RL_SECRET?: RateLimit;
  RL_PUBLISHABLE?: RateLimit;
  /**
   * Optional JSON override of the per-kind limits the worker advertises and
   * the in-memory limiter enforces, e.g.
   * `{"secret":{"limit":300,"period":60},"publishable":{"limit":120,"period":60}}`.
   * Must mirror the `ratelimits` entries when those bindings are present.
   */
  RATE_LIMITS?: string;
}

/**
 * The project columns the query path needs, read in the same statement as
 * the key (`requireApiKey`) so policy is fetched once per request.
 */
export interface ProjectPolicy {
  /** CORS allowlist for publishable keys (`projects.allowed_origins`). */
  allowedOrigins: string[];
  /** Publication policy floor on `rating` (`projects.min_rating`). */
  minRating: number;
  /** Cosine-similarity floor (`projects.similarity_floor`). */
  similarityFloor: number;
  /** Whether the snippet must render the badge (`projects.show_badge`). */
  showBadge: boolean;
}

/** What a resolved API key grants a request (set by `requireApiKey`). */
export interface AuthContext {
  apiKeyId: string;
  projectId: string;
  /** Scopes every row the request reads or writes. */
  environment: ApiKeyEnvironment;
  kind: ApiKeyKind;
  project: ProjectPolicy;
}

export interface AppVariables {
  /** Echoed as `x-request-id` on every response; in every error envelope. */
  requestId: string;
  /** Lazily opens the database for this request (see src/db.ts). */
  getDb: () => Db;
  /** Lazily resolves the query embedder for this request (see src/embedder.ts). */
  getEmbedder: () => EmbeddingProvider;
  /** Present after `requireApiKey` ran. */
  auth: AuthContext;
  /** Lazily resolves this request's per-kind limiters (see src/rate-limit.ts). */
  getRateLimiters: () => RateLimiters;
  /** Set by `markCacheHit` when the response was served from the cache. */
  cacheHit?: boolean;
}

/** Hono generic: bindings on `c.env`, variables on `c.var` / `c.get()`. */
export type AppEnv = { Bindings: ApiBindings; Variables: AppVariables };
