/**
 * Bindings the api worker receives as `env` — one entry per binding in
 * wrangler.jsonc (hand-written rather than generated by `wrangler types`, so
 * the shape is reviewed with the config that declares it) — and the
 * per-request variables middleware attaches to the Hono context.
 */

import type { EmbeddingProvider, Reranker } from "@proofql/ai";
import type {
  ApiKeyEnvironment,
  ApiKeyKind,
  IngestMessage,
  Logger,
  Plan,
} from "@proofql/core";
import type { Db } from "@proofql/db";

import type { RateLimiters } from "./rate-limit.js";
import type { UsageBuffer } from "./usage-buffer.js";

export interface ApiBindings {
  /** "local" | "preview" | "prod" — from `vars` in wrangler.jsonc. */
  ENVIRONMENT: string;
  /** Postgres via Hyperdrive; locally the docker compose database. */
  HYPERDRIVE: Hyperdrive;
  /** Query-result cache, shared with pipeline (purge) and dashboard (purge). */
  CACHE: KVNamespace;
  /** Producer side of `proofql-ingest`; workers/pipeline consumes. */
  INGEST_QUEUE: Queue<IngestMessage>;
  /**
   * Workers AI for query embeddings. Bound in preview/prod only — there is
   * no local simulator — so code must treat it as optional.
   */
  AI?: Ai;
  /**
   * `"true"` turns on experimental reranking of query candidates with
   * Workers AI bge-reranker-base (#147; src/query/rerank.ts). Unset by
   * default in every environment.
   */
  RERANK?: string;
  /** Reranker score threshold in [0, 1] when `RERANK` is on. */
  RERANK_THRESHOLD?: string;
  /**
   * Cloudflare rate limiting bindings, one per (plan, key kind) pair
   * (`ratelimits` in wrangler.jsonc). A binding's limit is fixed in the
   * config, so each plan needs its own pair; the numbers must mirror
   * `PLANS[plan].rateLimits` from @proofql/core (a unit test checks).
   * Optional: absent (unit tests, a wrangler without the config) the worker
   * falls back to an in-memory limiter per isolate so the behavior stays
   * observable locally. See src/rate-limit.ts.
   */
  RL_SECRET?: RateLimit;
  RL_PUBLISHABLE?: RateLimit;
  RL_SECRET_PAID?: RateLimit;
  RL_PUBLISHABLE_PAID?: RateLimit;
  /**
   * Per-IP budget of authentication failures (30 per 60 s; namespace 1005).
   * Same optional/fallback rule as the per-key bindings. See
   * src/auth-throttle.ts.
   */
  RL_AUTH_FAIL?: RateLimit;
}

/**
 * The project columns the query path needs, read in the same statement as
 * the key (`requireApiKey`) so policy is fetched once per request.
 */
export interface ProjectPolicy {
  /** CORS allowlist for publishable keys (`projects.allowed_origins`). */
  allowedOrigins: string[];
  /** Publication policy floor on `rating` (`projects.min_rating`). */
  minRating: number;
  /** Cosine-similarity floor (`projects.similarity_floor`). */
  similarityFloor: number;
}

/** What a resolved API key grants a request (set by `requireApiKey`). */
export interface AuthContext {
  apiKeyId: string;
  projectId: string;
  /** Scopes every row the request reads or writes. */
  environment: ApiKeyEnvironment;
  kind: ApiKeyKind;
  /**
   * The owning account's plan (`accounts.plan`), read with the key. Every
   * plan-driven decision on the request — the badge in the query response,
   * the rate limit, the monthly quota — derives from `planFor(plan)`;
   * `projects.show_badge` is only a cached mirror and is never read here.
   */
  plan: Plan;
  project: ProjectPolicy;
}

export interface AppVariables {
  /** Echoed as `x-request-id` on every response; in every error envelope. */
  requestId: string;
  /**
   * This request's structured logger, bound to `request_id`, `method`, and
   * `path` (see src/request-id.ts). The only way route code logs.
   */
  log: Logger;
  /** Lazily opens the database for this request (see src/db.ts). */
  getDb: () => Db;
  /** Lazily resolves the query embedder for this request (see src/embedder.ts). */
  getEmbedder: () => EmbeddingProvider;
  /** Lazily resolves the reranker, or null when none is available (src/embedder.ts). */
  getReranker: () => Reranker | null;
  /** Present after `requireApiKey` ran. */
  auth: AuthContext;
  /** Lazily resolves this request's per-kind limiters (see src/rate-limit.ts). */
  getRateLimiters: () => RateLimiters;
  /** Set by `markCacheHit` when the response was served from the KV cache. */
  cacheHit?: boolean;
  /**
   * The project's cache generation as read by `requireApiKey` when it
   * validated or stored the auth-cache entry (src/auth-cache.ts), so the
   * query cache key (src/query/cache.ts) reuses it instead of reading KV
   * again. Absent when auth did not read it (write routes, a KV fault).
   */
  projectGeneration?: number;
  /** The app's batched `usage` counters (src/usage-buffer.ts). */
  usage: UsageBuffer;
}

/** Hono generic: bindings on `c.env`, variables on `c.var` / `c.get()`. */
export type AppEnv = { Bindings: ApiBindings; Variables: AppVariables };
